### ISSUE TITLE
push_front semantics

### ISSUE THREAD

**Issue by user706** [user1095108/ca#6]
Hi,

I disagree with the `push_front` semantics:
https://github.com/user1095108/ca/blob/5dae347951ee2c7c7ec164dfefd87feb7b6406a3/array.hpp#L464

If it's full, the front does not move to prev, and we just overwrite the 1st element.

I always want front to move to prev (and have that as new 1st element, even if it means... overwriting the last element), so that the behaviour is analogue to `push_back` and other implementations such as `boost::circular_buffer`.

**Comment by user1095108** [comment]
That's true, but the behavior I implemented makes for simpler/faster code. You have to pay for everything and it would make for slightly slower/bulkier code.

**Comment by user706** [comment]
I don't think it's so much slower. (Seriously, are you trying to tell me you'll avoid your own `push_pack`, because your `push_front` is so much faster??!!!! Ok but I understand that you basically have 2 different semantics at the 2 differents ends: back and front -> that can also be useful [unless you explicitly want/need the same semantics at both ends)


```cpp
  template <int = 0>
  constexpr void push_front(auto&& v)
    noexcept(std::is_nothrow_assignable_v<value_type&, decltype(v)>)
    requires(std::is_assignable_v<value_type&, decltype(v)>)
  {
    *(f_ = prev(f_)) = std::forward<decltype(v)>(v);
    if (l_ == f_) pop_back();                      // semantics changed !!!
  }
```

**Comment by user1095108** [comment]
It's like this. I add newest data at the end `push_back()`, so the oldest is at the front and if you push something to the front and the deque is full, I overwrite the oldest data, which is at the front. Otherwise, you will overwrite the latest data, which, I suppose, is more valuable than the oldest.

So, the choice is whether to overwrite the most or least valuable (oldest) data and I choose the least valuable. You can obviously decide differently in your own code.

**Comment by user1095108** [comment]
Anyway, you're competent enough to implement your own queue discipline. If you decide to publish your work, I might decide to steal something from you.
